version: '3.4'
services:
  # Cria o banco de dados
  db-postgres-casa-facil:
    image: db-postgres-casa-facil
    build: ./Database
    container_name: "db-postgres-casa-facil"
    restart: on-failure
    env_file: ./common.env
    ports:
      - 15432:5432
    networks:
      - casa-facil-network
  # Cria a interface do PGAdmin 4
  db-pgadmin-casa-facil:
    image: dpage/pgadmin4
    container_name: "db-pgadmin-casa-facil"
    restart: on-failure
    env_file: ./common.env
    ports:
      - 16543:80
    networks:
      - casa-facil-network
  # Cria o back-end
  back-end-casa-facil:
    image: back-end-casa-facil
    container_name: "back-end-casa-facil"
    restart: on-failure
    env_file: ./common.env
    build:
      context: ./Back-end
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db-postgres-casa-facil
    networks:
      - casa-facil-network
  front-end-casa-facil:
    image: front-end-casa-facil
    container_name: "front-end-casa-facil"
    restart: on-failure
    environment:
      - BACKEND_URL=back-end-casa-facil
    build:
      context: ./Front-end/casa-facil
      dockerfile: ./Dockerfile
    depends_on:
      - back-end-casa-facil
    ports:
      - 5000:80
networks:
  casa-facil-network:
    driver: bridge