FROM maven:3.5.4-jdk-10-slim
# Pasta de trabalho
WORKDIR /usr/src/java-code
# Copia o back-end para a pasta java-code
COPY . /usr/src/java-code/
# Executa o comando package pulando os testes
RUN mvn package -DskipTests

# Defini a pasta de trabalho
WORKDIR /usr/src/java-app
# Executa a cópia do jar gerado para o app.jar
RUN cp /usr/src/java-code/target/*.jar ./app.jar
# Expões a porta 8080
EXPOSE 8080
# Executa os comandos quando o app subir
CMD ["java", "-jar", "app.jar"]